#ifndef __AUTOUPDATE_APP_INFO__H
#define __AUTOUPDATE_APP_INFO__H

#ifdef _WIN32
#pragma once
#endif

#define AUTOUPDATE_APP_NAME "Pepe"
#define AUTOUPDATE_APP_FILENAME "pepe.jpg"

#define AUTOUPDATE_APP_MAJOR_VERSION ( 1 )
#define AUTOUPDATE_APP_MINOR_VERSION ( 0 )
#define AUTOUPDATE_APP_PATCH_VERSION ( 0 )

#define AUTOUPDATE_APP_MAJOR_VERSION_STRING "1"
#define AUTOUPDATE_APP_MINOR_VERSION_STRING "0"
#define AUTOUPDATE_APP_PATCH_VERSION_STRING "0"

#define AUTOUPDATE_APP_VERSION_STRING AUTOUPDATE_APP_MAJOR_VERSION_STRING "." AUTOUPDATE_APP_MINOR_VERSION_STRING "." AUTOUPDATE_APP_PATCH_VERSION_STRING

#endif